databases:
  - name: mysite_db
    databaseName: mysite
    user: mysite_user

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
